### ISSUE TITLE
Replace sccache by something more reliable, as caching with sccache does not work on windows

### ISSUE THREAD

**Issue by hrzlgnm** [hrzlgnm/mdns-browser#924]

**Comment by hrzlgnm** [comment]
Something like
```yaml  
 - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/master' }}
          workspaces: |
            shared_constants -> ./target
            models -> ./target
            src-tauri -> ./target
```
